# Generated by Django 2.0.8 on 2018-09-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oppurtunities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('type', models.CharField(choices=[('govt', 'GOVT'), ('private', 'PRIVATE')], default='govt', max_length=7)),
                ('brief_info', models.TextField(max_length=1000)),
                ('age_criteria', models.IntegerField()),
                ('gender_criteria', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('both', 'BOTH')], default='both', max_length=6)),
            ],
        ),
    ]
