# Generated by Django 2.0.8 on 2018-10-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('type', models.CharField(choices=[('govt', 'GOVT'), ('private', 'PRIVATE')], default='govt', max_length=7)),
                ('brief_info', models.TextField(max_length=1000)),
                ('age_criteria', models.IntegerField()),
                ('gender_criteria', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('both', 'BOTH')], default='both', max_length=6)),
                ('annual_income_range', models.IntegerField()),
                ('source_of_livelihood', models.CharField(choices=[('agriculture', 'AGRI'), ('daily wage', 'DAILY WAGE'), ('salaried in private', 'SALARIED PRIVATE'), ('unemployed', 'UNEMPLOYED')], default='UNEMPLOYED', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Oppurtunities',
        ),
    ]
