# Generated by Django 2.0.8 on 2018-10-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20181027_0743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opportunity',
            new_name='Scheme',
        ),
    ]
