# Generated by Django 2.0.8 on 2018-12-09 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20181028_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caste', models.CharField(choices=[('sc', 'Sheduled Caste'), ('st', 'Scheduled Tribes'), ('obc', 'Other backward Classes'), ('gen', 'General')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('edu', 'Education'), ('emp', 'Employment'), ('women', 'Women')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(choices=[('agriculture', 'AGRI'), ('daily wage', 'DAILY WAGE'), ('salaried in private', 'SALARIED PRIVATE'), ('unemployed', 'UNEMPLOYED')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_ministry', models.CharField(choices=[('MAFW', 'Ministry of Farmers Welfare'), ('MAY', 'Ministry of Ayush'), ('MCF', 'Ministry of Chemical & Fertilizers'), ('MCA', 'Ministry of Civil Aviation'), ('MCOAL', 'Ministry of Coal'), ('MCOMMERCE', 'Ministry of Commerce'), ('MCOMMUNICATION', 'Ministry of Communication'), ('MCAFPD', 'Ministry of Consumer Affairs, Food and Public Distribution'), ('MCA', 'Ministry of Corporate Affairs'), ('MCULTURE', 'Ministry of Culture'), ('MD', 'Ministry of Defence'), ('MDNER', 'Ministry of Development of North Eastern Region'), ('MDWS', 'Ministry of Drinking Water and Santitation'), ('MES', 'Ministry of Earth Sciences'), ('MEIT', 'Ministry of Electronis anf IT'), ('MEFCC', 'Ministry of Environment, Forest & Climate Change'), ('MEA', 'Ministry of External Affairs'), ('MF', 'Ministry of Finance'), ('MFPI', 'Ministry of Food Processing Industry'), ('MHFW', 'Ministry of Health & Family Welfare'), ('MHIPE', 'Ministry of Heavy Industries & Public Enterprise'), ('MHA', 'Ministry of Home Affairs'), ('MHUA', 'Ministry of Housing and Urban Affairs'), ('MHRD', 'Ministry of Rural Development'), ('MLE', 'Ministry of Labour and Employment'), ('MLJ', 'Ministry of Law and Justice'), ('MPPGP', 'Ministry of Personell, Public Grievences and Pensions'), ('MPNG', 'Ministry of Petroleum and Natural Gas'), ('MP', 'Ministry of Power'), ('MR', 'Ministry of Railways'), ('MRTH', 'Ministry of Road Transport & Highways'), ('MRD', 'Ministry of Rural Development'), ('MST', 'Ministry of Science & Technology'), ('MS', 'Ministry of Shipping'), ('MSDE', 'Ministry of Skill Development & Entrepreneurship'), ('MSJE', 'Ministry of  Social Justice & Empowerment'), ('MSPI', 'Ministry of Statistics & Program Implementation'), ('MS', 'Ministry of Steel'), ('MT', 'Ministry of Textile'), ('MTOURISM', 'Ministry of Tourism'), ('MTA', 'Ministry of Tribal Affairs')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Typ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_scheme', models.CharField(choices=[('govt', 'Govt'), ('non-govt', 'Non-Govt')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='age_criteria',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='gender_criteria',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='type',
        ),
        migrations.AddField(
            model_name='scheme',
            name='age',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='scheme',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('both', 'BOTH')], default='male', max_length=6),
        ),
        migrations.AddField(
            model_name='scheme',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=50)),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='annual_income_range',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='source_of_livelihood',
            field=models.ForeignKey(help_text='Select typ of job', null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.Job'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='caste',
            field=models.ForeignKey(help_text='Select typ of caste', null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.Caste'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='category',
            field=models.ManyToManyField(help_text='Select category :Education/Health/Employment', to='search.Category'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='ministry',
            field=models.ForeignKey(help_text='Select ministry', null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.Ministry'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='typ',
            field=models.ForeignKey(help_text='Select type :Govt/Non-Govt', null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.Typ'),
        ),
    ]
