# Generated by Django 2.0.8 on 2018-12-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20181210_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='age',
            field=models.IntegerField(default=18, help_text='enter age'),
        ),
    ]
