# Generated by Django 2.0.8 on 2018-12-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20181210_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='age',
            field=models.IntegerField(help_text='enter age', null=True),
        ),
    ]
